### ISSUE TITLE
[MEAR-33] add option to include modules in EAR in exploded (i.e. directory) form, rather than as in jar form

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-ear-plugin#230]
**[Ian P. Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ips)** opened **[MEAR-33](https://issues.apache.org/jira/browse/MEAR-33?redirect=false)** and commented

In JBoss, and perhaps other app servers, modules can be packaged in an EAR as directories. For example:

my.ear/
my.war/
service1.sar/
service2.sar/

Please add an option on the ear plugin that allows you to specify that modules should be packaged in exploded form.

---

**Affects:** 2.2

**Attachments:**
- [MEAR-33.patch](https://issues.apache.org/jira/secure/attachment/12715815/MEAR-33.patch) (_2.87 kB_)

**Comment by jira-importer** [comment]
**[Ian P. Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ips)** commented

Here's a patch that implements the requested feature.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

I don't get this one. It should help if the EAR itself was exploded, which is not the case right now.

**Comment by jira-importer** [comment]
**[Ian P. Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ips)** commented

Right, in my case, the EAR will ultimately be exploded in my product's distribution, and I also want all of the sub J2EE modules to be exploded under the EAR directory. I think the logical way to make this happen is to explode the sub modules during construction of the EAR, even if the EAR will be zipped up in order to install the EAR artifact to the local repo. That way, all I'd have to do in my assembly phase, is unzip the EAR to the correct place in my distribution, rather than having to repackage all of the sub modules as directories during assembly.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Sounds good to me. Will add an exploded goal as well.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Done. Two ways to configure this

* Add: \<unpack>true\</unpack> to the module's configuration
* Specify a list of types that will be unpacked, \<unpackTypes>rar,ejb,war\</unpackTypes>

**Comment by jira-importer** [comment]
**[Ian P. Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ips)** commented

I just build 2.3-SNAPSHOT and tried this out. I added the following setting to my ear-plugin config:

\<unpackTypes>ejb,war,sar\</unpackTypes>

But when I run mvn install, I get the following error:

[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] No Archiver found for EAR modules

Embedded error: No such archiver: 'sar'.
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: No Archiver found for EA
R modules
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:559)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.MojoExecutionException: No Archiver found for
EAR modules
at org.apache.maven.plugin.ear.EarMojo.execute(EarMojo.java:208)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:534)
... 16 more
Caused by: org.codehaus.plexus.archiver.manager.NoSuchArchiverException: No such
archiver: 'sar'.
at org.codehaus.plexus.archiver.manager.DefaultArchiverManager.getUnArch
iver(DefaultArchiverManager.java:80)
at org.codehaus.plexus.archiver.manager.DefaultArchiverManager.getUnArch
iver(DefaultArchiverManager.java:114)
at org.apache.maven.plugin.ear.EarMojo.unpack(EarMojo.java:382)
at org.apache.maven.plugin.ear.EarMojo.execute(EarMojo.java:189)
... 18 more

It looks like the plexus-archiver needs to be updated to grok the sar extension.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

come on :(

OK, I'll have a look to use a more general type.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

reproduced with test case project-04

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Voila. I added a test case to reproduce the problem and we know use a more general type to unpack archives (e.g. zip)

**Comment by jira-importer** [comment]
**[Harald Soevik](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hso)** commented

I cannot find a way to explode an artifact when a project is directly dependent on artifact B and transitively dependent on A.

Either A cannot be exploded because it is not defined as direct dependency, or A cannot be included as transitive dependency because it has already been exploded as a direct dependency.

Might be worth a fix ?

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

?? Not sure I understand

The fact that it's transitive does not make any difference. Just configure the module with the exploded flag to true.
