### ISSUE TITLE
[MEAR-130] maven build hangs when earSourceDirectory is set to /

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-ear-plugin#313]
**[Cremers stijn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cremersstijn)** opened **[MEAR-130](https://issues.apache.org/jira/browse/MEAR-130?redirect=false)** and commented

When building a maven project with apache-maven-3.0-beta-2, the build hangs on "[INFO] Copy ear sources to".

This is only when the \<earSourceDirectory>/\</earSourceDirectory> is specified.

A log file with the maven output is attached

---

**Affects:** 2.4.1

**Attachments:**
- [DEV_V01.00.00.zip](https://issues.apache.org/jira/secure/attachment/12715736/DEV_V01.00.00.zip) (_7.93 kB_)
- [maven.log](https://issues.apache.org/jira/secure/attachment/12715833/maven.log) (_23.26 kB_)

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Thanks for the report. Can you attach a sample project that reproduces the issue? thanks.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

I can reproduce, thanks

Here is the thread dump

```
"main" prio=5 tid=102800800 nid=0x100501000 runnable [1004fb000]
   java.lang.Thread.State: RUNNABLE
	at java.util.StringTokenizer.scanToken(StringTokenizer.java:261)
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:334)
	at org.codehaus.plexus.util.SelectorUtils.tokenizePath(SelectorUtils.java:665)
	at org.codehaus.plexus.util.SelectorUtils.matchAntPathPattern(SelectorUtils.java:290)
	at org.codehaus.plexus.util.SelectorUtils.matchPath(SelectorUtils.java:273)
	at org.codehaus.plexus.util.AbstractScanner.matchPath(AbstractScanner.java:216)
	at org.codehaus.plexus.util.AbstractScanner.isExcluded(AbstractScanner.java:405)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:476)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:483)
	at org.codehaus.plexus.util.DirectoryScanner.scan(DirectoryScanner.java:332)
	at org.apache.maven.plugin.ear.EarMojo.getEarFiles(EarMojo.java:528)
	at org.apache.maven.plugin.ear.EarMojo.execute(EarMojo.java:340)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:107)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:88)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:80)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:87)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:315)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

**Comment by jira-importer** [comment]
**[Cremers stijn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cremersstijn)** commented

It works with maven 2.0.9!

This is what i'm trying to accomplish:
The is my ear project:
mvn3-ear/
mvn3-ear/lib/
mvn3-ear/lib/*(all libs)
mvn3-ear/META-INF/application.xml
mvn3-ear/META-INF/ibm-application-bnd.xmi

The ibm-application-bnd.xmi must be included in the with maven generated ear.
So this my configuration
\<plugin>
\<artifactId>maven-ear-plugin\</artifactId>
\<configuration>
...
\<earSourceDirectory>/\</earSourceDirectory>
\<earSourceIncludes>**/META-INF/ibm-application-bnd.xmi\</earSourceIncludes>
\</configuration>
\</plugin>

It do not want to scan the whole drive, but just the mvn3-ear project.
