### ISSUE TITLE
[MEAR-212] Failed to initialize ear modules: Unknown artifact type[mar] for addressing

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-ear-plugin#382]
**[David Hoffer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dahoffer)** opened **[MEAR-212](https://issues.apache.org/jira/browse/MEAR-212?redirect=false)** and commented

I'm trying to generate and ear file but I'm getting the following message:  Failed to initialize ear modules: Unknown artifact type[mar] for addressing  (full debug stack trace is below)

However I don't have any mar artifacts in my dependencies.  What I do have is a war that has 4 mar files added as resources and I'm making a ear with the skinny war feature.

Why would the ear plugin give this error when it has no nothing to do with the mar resources in the war...or perhaps this error has nothing to do with those resources, not sure.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-ear-plugin:2.10:generate-application-xml (default-generate-application-xml) on project coreservices-ear: Failed to initialize ear modules: Unknown artifact type[mar] for addressing -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-ear-plugin:2.10:generate-application-xml (default-generate-application-xml) on project coreservices-ear: Failed to initialize ear modules
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to initialize ear modules
	at org.apache.maven.plugin.ear.AbstractEarMojo.execute(AbstractEarMojo.java:260)
	at org.apache.maven.plugin.ear.GenerateApplicationXmlMojo.execute(GenerateApplicationXmlMojo.java:162)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.maven.plugin.ear.UnknownArtifactTypeException: Unknown artifact type[mar] for addressing
	at org.apache.maven.plugin.ear.EarModuleFactory.newEarModule(EarModuleFactory.java:88)
	at org.apache.maven.plugin.ear.AbstractEarMojo.execute(AbstractEarMojo.java:250)
	... 22 more
```

---

**Affects:** 2.10

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

If we really need this we have to find out how a `MAR` file looks like and create a separate plugin to create such kind of files and afterwards we can enhance maven-ear-plugin accordingly.

**Comment by jira-importer** [comment]
**[Marat Abrarov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abrarovm)** commented

[David Hoffer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dahoffer), could [that workaround](https://issues.apache.org/jira/browse/MEAR-216?focusedCommentId=17195895&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17195895) (custom type mapping of EAR modules) from MEAR-216 work for you?

**Comment by elharo** [comment]
per llm "A MAR file in the context of Java is typically associated with the Apache Axis2 framework, where it is used to package modules or services. It is similar to a JAR file but specifically designed for Axis2 applications."

**Comment by elharo** [comment]
10 years in I doubt we'll add this. Gemini elaborates:

The feature proposed in [[issue #382](https://github.com/apache/maven-ear-plugin/issues/382)](https://github.com/apache/maven-ear-plugin/issues/382) (originally tracked as MEAR-212) requests native support for the `mar` (Axis2 Module Archive) artifact type in the Maven EAR Plugin to prevent the build from failing with a `Failed to initialize ear modules: Unknown artifact type[mar]` error.

Implementing native support for this specific artifact type within the plugin is not worthwhile for two primary reasons:

1. **Lack of Specification Alignment:** The Java EE and Jakarta EE specifications for Enterprise Archives (EAR) strictly define standard module types such as `jar`, `war`, `ejb`, `rar`, and `app-client`. Java EE application servers do not possess native deployment semantics for Axis2 `.mar` files at the EAR root level.
2. **Existing Configuration Mechanism:** The Maven EAR Plugin already includes a built-in feature to handle custom or framework-specific artifact types without requiring source code modifications to the plugin itself.

Users encountering the `Unknown artifact type[mar]` error can resolve it immediately by mapping the custom `mar` extension to the standard `jar` type using the `<artifactTypeMappings>` parameter. This configuration instructs the plugin to package the `.mar` file exactly as it would a standard Java library.

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-ear-plugin</artifactId>
  <version>3.4.0</version> <!-- Replace with your current version -->
  <configuration>
    <artifactTypeMappings>
      <artifactTypeMapping type="mar" mapping="jar" />
    </artifactTypeMappings>
  </configuration>
</plugin>

```

Because this explicit workaround exists in the standard configuration, and `.mar` is a proprietary archive format rather than an industry standard, expanding the plugin's internal artifact handlers to accommodate it natively adds unnecessary complexity with no distinct operational advantage.
